<div class="container">
  <!-- Header -->
  <div class="row">
    <?php $this->renderView('alerts/_success');?>
    <?php $this->renderView('alerts/_errors');?>
  </div>
  <header class="text-center">
    <div class="container">
      <img class="img-responsive center-block" src="/myframework.png" alt="">
      <h1>Myframework</h1>
      <hr class="star-light">
      <h2 class="font-weight-light mb-0">Framework feito em PHP para estudos - Dev: Jorge Toledo</h2>
    </div>
  </header>
</div>

