<?php if($this->success) : ?>
  <div class="alert alert-success alert-dismisible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <?php foreach($this->success as $msg) : ?>
      <i class="class glyphicon glyphicon-ok-sign"></i><?php echo $msg; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>