<div class="container">
  <h1><?php echo $this->getPageTitle(); ?></h1>

  <form action="/post/<?php echo $this->view->post->id ?>/update" method="post">
    <div class="form-group <?php echo ($this->errors['title']) ? 'has-error' : '' ?>">
      <label class="control-label" for="title">Title</label>
      <input type="text" name="title" class="form-control" value="<?php echo (isset($this->inputs['title'])) ? $this->inputs['title'] : $this->view->post->title; ?>">    
      <?php if($this->errors['title']) : ?>
        <span class="help-block"><?php echo $this->errors['title']; ?></span>
      <?php endif; ?>
    </div>

    <div class="form-group <?php echo ($this->errors['content']) ? 'has-error' : '' ?>">
      <label class="control-label" for="content">Content</label>
      <textarea name="content" rows="15" class="form-control"><?php echo (isset($this->inputs['content'])) ? $this->inputs['content'] : $this->view->post->content; ?></textarea>
      <?php if($this->errors['content']) : ?>
        <span class="help-block"><?php echo $this->errors['content']; ?></span>
      <?php endif; ?>
    </div>
    
    <a href="/posts" class="btn btn-default">Cancel</a>
    <button type="submit" class="btn btn-primary">Save</button>  
  </form>
</div>